### ISSUE TITLE
Cannot write mode RGBA as JPG.

### ISSUE THREAD

**Issue by ysig** [reidsanders/danbooru-utility#1]
I have the following problem one various files while using your utility:
Cannot write mode RGBA as JPG.
I know what it means but I would like to fix it inside your code but I don't know how.

**Comment by reidsanders** [comment]
Can you post the error and the command that causes this error? The image should save as the same format it was loaded in, and a jpg cannot have an alpha channel. Possibly some sort of incorrectly formatted image. 

As a temporary fix you could force it to save as png, eg
>  img.save(write_path, "png")

If you want to always remove the alpha channel you could add img.convert("RGB") before the img.save (~line 358). You could also hardcode jpg as the output format in that case.

**Comment by ysig** [comment]
Yep this worked!
Thanks
